### PR TITLE
Remove kerning hack in Czech translation

### PR DESCRIPTION
**Pull request by nextghost**
I've removed the obsolete kerning hack around letter "í". There's no need to render this, it's just a little cleanup so that Czech translation renders the same as before with fixed Lavi font.

### CODE REVIEW

**Comment by nextghost** [comment]
Damn, I knew I should have bumped this update together with Ep3 translation. I didn't expect you to make fresh render of this episode before somebody submits a new translation. Anyway, I've reapplied the kerning fix to the latest version of SVGs. I've also moved one of the SFX texts a little so it doesn't blend in too much with the drawing.

**Comment by Deevad** [comment]
Ooops! Sorry. I missed them and now with the new layout refactored I guess this Pull-Request is obsolete. Sorry again and let me know if I can help.

**Comment by nextghost** [comment]
I've updated the pull request today to apply on the new paged layout. You can merge this.

**Comment by Deevad** [comment]
:+1:  thank you!
I'm rendering right now the pages, and I'll upload them in the next 30min. Thank you for your time.

**Pull request merged**
