### PR TITLE
Added Serbian translation

### PR DESCRIPTION
**Pull request by mitinica**
Hi. I translated the second episode, hope everything is OK. :)

### CODE REVIEW

**Comment by Deevad** [comment]
I'll render and push it online in the next 30 min , we'll see :)
Thank you !

**Comment by Deevad** [comment]
All look per~~~fect! Congratz : http://www.peppercarrot.com/sr/article237/episode-2-rainbow-potions , Thank you for this hi-quality pull-request. It's a breeze to push them online :) Have a good sunday!

**Comment by mitinica** [comment]
I am glad everything is ok. :D More translated episodes coming soon!

**Comment by Deevad** [comment]
:+1: super!

**Pull request merged**
