### PR TITLE
IT Translation

### PR DESCRIPTION
**Pull request by cgand**
Ep. 2 translated to italian

### CODE REVIEW

**Comment by cgand** [comment]
Ep. 2 translated to italian

**Comment by Deevad** [comment]
Hi @cgand ( Carlo ? right! Just to be sure! ) This pull-request looks really good, exept you closed it :-)
Thank you for all the time you take to learn how to contribute to Pepper&Carrot via Github ; I appreciate it a lot!

**Comment by Deevad** [comment]
Ok! I could reopen the pull-request ( my comment auto-reopened it ) and I merged it to master. 
I'll now try to render the hi-res and low-res jpg and upload them on official website :+1:

**Comment by cgand** [comment]
Thanks sorry for my mistake.

**Comment by cgand** [comment]
On Tue, May 5, 2015 at 1:27 PM, David Revoy notifications@github.com
wrote:

> Ok! I could reopen the pull-request ( my comment auto-reopened it ) and I
> merged it to master
> 
> Thanks, sorry for my mistake, I'll go ahead with the other episodes.
> Does it worth create a branch "IT-Translation" other than master?

Thanks,
Carlo

**Comment by Deevad** [comment]
Hey, it's online and the files were perfect! 
http://www.peppercarrot.com/it/article237/episode-2-rainbow-potions

Thank you, it ease a lot of the process to receive them this way.
Feel free to keep working to 'master' and not in another branch. Pull-request are a good tool, because they allow two contributors to work on the same repository without conflict. The only file in conflict is often the README.md, but the merging is really easy because it's just a text file.
You can go ahead ! 
Thanks again
(Note: I sent an email to Antonio who started also Italian translation of episode 1 last week to tell him you were working on completing the other episodes, and he was happy to get the notice before starting duplicate work. He is working now on a EPUB version for ebook )

**Pull request merged**
